config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"

  devise_for :users

  resources :products do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:show, :index]
  resources :special_offers
  resources :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/special_offer.rb
class SpecialOffer < ApplicationRecord
end

app/controllers/special_offers_controller.rb
class SpecialOffersController < ApplicationController
  before_action :set_special_offer, only: [:show, :edit, :update, :destroy]

  # GET /special_offers
  # GET /special_offers.json
  def index
    @special_offers = SpecialOffer.all
  end

  # GET /special_offers/1
  # GET /special_offers/1.json
  def show
  end

  # GET /special_offers/new
  def new
    @special_offer = SpecialOffer.new
  end

  # GET /special_offers/1/edit
  def edit
  end

  # POST /special_offers
  # POST /special_offers.json
  def create
    @special_offer = SpecialOffer.new(special_offer_params)

    respond_to do |format|
      if @special_offer.save
        format.html { redirect_to @special_offer, notice: 'Special offer was successfully created.' }
        format.json { render :show, status: :created, location: @special_offer }
      else
        format.html { render :new }
        format.json { render json: @special_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /special_offers/1
  # PATCH/PUT /special_offers/1.json
  def update
    respond_to do |format|
      if @special_offer.update(special_offer_params)
        format.html { redirect_to @special_offer, notice: 'Special offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @special_offer }
      else
        format.html { render :edit }
        format.json { render json: @special_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /special_offers/1
  # DELETE /special_offers/1.json
  def destroy
    @special_offer.destroy
    respond_to do |format|
      format.html { redirect_to special_offers_url, notice: 'Special offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_special_offer
      @special_offer = SpecialOffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def special_offer_params
      params.require(:special_offer).permit(:discount, :date_from, :date_to)
    end
end

app/views/special_offers/_form.html.erb
<%= form_for(special_offer) do |f| %>
  <% if special_offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(special_offer.errors.count, "error") %> prohibited this special_offer from being saved:</h2>

      <ul>
      <% special_offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :discount %>
    <%= f.number_field :discount %>
  </div>

  <div class="field">
    <%= f.label :date_from %>
    <%= f.datetime_select :date_from %>
  </div>

  <div class="field">
    <%= f.label :date_to %>
    <%= f.datetime_select :date_to %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/special_offers/edit.html.erb
<h1>Editing Special Offer</h1>

<%= render 'form', special_offer: @special_offer %>

<%= link_to 'Show', special_offer_path(@special_offer) %> |
<%= link_to 'Back', special_offers_path %>

app/views/special_offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Special Offers</h1>

<table>
  <thead>
    <tr>
      <th>Discount</th>
      <th>Date from</th>
      <th>Date to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @special_offers.each do |special_offer| %>
      <tr>
        <td><%= special_offer.discount %></td>
        <td><%= special_offer.date_from %></td>
        <td><%= special_offer.date_to %></td>
        <td><%= link_to 'Show', special_offer_path(special_offer) %></td>
        <td><%= link_to 'Edit', edit_special_offer_path(special_offer) %></td>
        <td><%= link_to 'Destroy', special_offer_path(special_offer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Special Offer', new_special_offer_path %>

app/views/special_offers/new.html.erb
<h1>New Special Offer</h1>

<%= render 'form', special_offer: @special_offer %>

<%= link_to 'Back', special_offers_path %>

app/views/special_offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discount:</strong>
  <%= @special_offer.discount %>
</p>

<p>
  <strong>Date from:</strong>
  <%= @special_offer.date_from %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @special_offer.date_to %>
</p>

<%= link_to 'Edit', edit_special_offer_path(@special_offer) %> |
<%= link_to 'Back', special_offers_path %>