config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"

  devise_for :users

  resources :products do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:show, :index]
  resources :special_offers
  resources :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user

  before_save :set_fields

  validates :user, :product, :quantity, :total_price, :payment_status, presence: true
  validates :quantity, :total_price, numericality: { greater_than: 0 }
  validate :product_is_available

  private

  def set_fields
    self.price = product.price
    if user.instant_payment_allowed
      self.payment_status = "processed"
    else
      self.payment_status = "pending"
    end
  end

  def product_is_available
    if product.quantity_in_stock < quantity
      errors.add(:product_amount, "can't be greater than #{product.quantity_in_stock}")
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:new, :create]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new(product: @product)
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.product = @product
    @order.user = current_user

    current_discounts = SpecialOffer.where("date_from < ? AND date_to > ?", DateTime.now, DateTime.now)
    total_discount = current_discounts.map(&:discount).reduce(0, :+)
    total_price_before_discount = @order.quantity * @product.price
    total_price_after_discount = total_price_before_discount - (total_price_before_discount * total_discount / 100)
    @order.total_price = total_price_after_discount

    respond_to do |format|
      if @order.save
        @product.update(quantity_in_stock: @product.quantity_in_stock - order_params[:quantity].to_i)
        OrderMailer.shop_owner_order_notification(@order).deliver!
        SendOrderPaymentNotificationWorker.perform_in(24.hours, @order)

        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        puts "Error log: Order could not be created. Errors: #{@order.errors}"

        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:quantity)
    end
end

app/views/orders/_form.html.erb
<%= form_for([@product, @order]) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>User</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total price</th>
      <th>Payment status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product.full_name %></td>
        <td><%= order.user.email %></td>
        <td><%= order.price %></td>
        <td><%= order.quantity %></td>
        <td><%= order.total_price.round(2) %></td>
        <td><%= order.payment_status %></td>
        <td><%= link_to 'Show', order_path(order) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order.product.full_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user.email %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price.round(2) %>
</p>

<p>
  <strong>Payment status:</strong>
  <%= @order.payment_status %>
</p>

<%= link_to 'Back', orders_path %>