config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"

  devise_for :users

  resources :products do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:show, :index]
  resources :special_offers
  resources :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :brand, :model, :price, :quantity_in_stock, presence: true
  validates :price, :quantity_in_stock, numericality: { greater_than: 0 }

  def full_name
    "#{brand} #{model}"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:brand, :model, :price, :quantity_in_stock)
    end
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :quantity_in_stock %>
    <%= f.number_field :quantity_in_stock %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Price</th>
      <th>Quantity in stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.brand %></td>
        <td><%= product.model %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity_in_stock %></td>
        <% if current_user && current_user.admin? %>
          <td><%= link_to 'Show', product_path(product) %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% elsif current_user %>
          <td><%= link_to 'Order', new_product_order_path(product) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.admin? %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @product.model %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity in stock:</strong>
  <%= @product.quantity_in_stock %>
</p>


<% if current_user && current_user.admin? %>
  <%= link_to 'Edit', edit_product_path(@product) %>
<% end %>
<%= link_to 'Back', products_path %>